### ISSUE TITLE
How to build the kernel source?

### ISSUE THREAD

**Issue by nkymey** [KyuoFoxHuyu/android_kernel_xiaomi_sm8350#1]
The Patch based on QualComm release TAG:LA.UM.9.14.r1-10000-LAHAINA.0
The kernel config file used is venus_QGKI.config

How to build with venus_QGKI.config?

Thanks

**Comment by nkymey** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/2186

**Comment by benja95** [comment]
did you manage to make the phone boot? my Mi11 only boots without touchscreen, battery and other modules
